# -*- coding: utf-8 -*-
"""New.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_-8oqjOn7eZYHIIL9dzsILywTzUV6JN

##Подготовка

###Библиотеки
"""

# !pip install pandas openpyxl reportlab beautifulsoup4

import os
import re
import pandas as pd
from bs4 import BeautifulSoup
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from openpyxl.styles import Alignment, PatternFill
from openpyxl.utils import get_column_letter
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

"""###Парсинг HTML"""

def parse_grade_data(html_content):
    """Сбор данных из HTML страницы (из отчеты_д.py)"""
    soup = BeautifulSoup(html_content, 'html.parser')

    # Извлечение названия группы
    group_match = re.search(r'Сводная ведомость для группы:\s*<b>(.*?)</b>', str(soup))
    group_name = group_match.group(1).strip() if group_match else "Неизвестная группа"

    # Парсинг студентов
    header_table = soup.find('table', {'id': 'cabinet_for_curator_table_top'})
    students = []
    if header_table:
        student_cells = header_table.find_all('th')
        for cell in student_cells:
            name = cell.get_text(strip=True)
            if name and name != '-':
                students.append(name)

    # Парсинг предметов
    left_table = soup.find('table', {'id': 'cabinet_for_curator_table_left'})
    subjects = []
    current_semester = ""

    if left_table:
        rows = left_table.find_all('tr')
        for row in rows:
            semester_cell = row.find('td', class_='semester')
            if semester_cell:
                current_semester = semester_cell.get_text(strip=True)
                continue

            cells = row.find_all('td')
            if len(cells) >= 2:
                subject_id = cells[0].get_text(strip=True)
                subject_name_full = cells[1].get_text(strip=True)
                if subject_id.isdigit() and subject_name_full:
                    # Извлечение типа предмета из последних скобок
                    subject_type = ""
                    subject_name_clean = subject_name_full

                    # Ищем последние скобки
                    if '(' in subject_name_full and ')' in subject_name_full:
                        # Находим последнюю открывающую скобку
                        last_open_bracket = subject_name_full.rfind('(')
                        last_close_bracket = subject_name_full.rfind(')')

                        if last_open_bracket != -1 and last_close_bracket != -1 and last_close_bracket > last_open_bracket:
                            subject_type = subject_name_full[last_open_bracket + 1:last_close_bracket].strip()
                            subject_name_clean = subject_name_full[:last_open_bracket].strip()

                    subjects.append({
                        'id': int(subject_id),
                        'name': subject_name_clean,
                        'type': subject_type,
                        'semester': current_semester
                    })

    # Парсинг оценок
    grades_data = {}
    table = soup.find('table', {'id': 'cabinet_for_curator_table'})

    if table:
        rows = table.find_all('tr')
        for row in rows:
            row_id = row.get('id')
            if row_id and row_id.startswith('row_'):
                row_num = int(row_id.split('_')[1])
                grade_cells = row.find_all('td')

                for col_num, cell in enumerate(grade_cells):
                    if col_num < len(students):
                        grade = cell.get_text(strip=True)
                        student = students[col_num]
                        if student not in grades_data:
                            grades_data[student] = {}
                        grades_data[student][row_num] = grade

    # Создание DataFrame
    data = []
    for subject in subjects:
        row_data = {
            'Дисциплина': subject['name'],
            'Тип': subject['type'],
            'Семестр': subject['semester']
        }
        for student in students:
            row_data[student] = grades_data.get(student, {}).get(subject['id'], '')
        data.append(row_data)

    df = pd.DataFrame(data)
    return df, group_name

"""###Проверка на задолженности"""

def is_debtor(grade: str) -> bool:
    """Проверка, является ли оценка долгом"""
    return str(grade).lower() in {'н/з', 'неуд.', 'н/а', ''}

"""###Форматирование эксельки"""

from openpyxl.styles import Alignment, PatternFill
from openpyxl.utils import get_column_letter

def df_to_excel_autoresize(df: pd.DataFrame, filepath: str, highlight_debtors: bool = True, individual: bool = False):
    """
    Сохраняет DataFrame в Excel с:
    - переносом текста по словам,
    - автоподбором ширины столбцов,
    - подсветкой долгов:
        * individual=True  → подсвечивается ВСЯ СТРОКА, если в ней есть долг,
        * individual=False → подсвечиваются ТОЛЬКО ячейки с долгами.
    """
    with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Sheet1')
        worksheet = writer.sheets['Sheet1']

        # Стили
        wrap_align = Alignment(wrap_text=True, vertical='top')
        red_fill = PatternFill(start_color="FFCCCC", end_color="FFCCCC", fill_type="solid")

        # Определяем столбцы студентов (всё, кроме служебных)
        student_cols = [col for col in df.columns if col not in {'Дисциплина', 'Тип', 'Семестр'}]
        student_col_indices = {col: i + 1 for i, col in enumerate(df.columns)}  # Excel: 1-based

        # Проходим по строкам
        for row_idx, (_, row) in enumerate(df.iterrows(), start=2):
            # Определяем, есть ли долг в строке (только среди студентов)
            has_debt_in_row = any(
                is_debtor(row[col]) for col in student_cols if col in row
            )

            for col_idx, col_name in enumerate(df.columns, start=1):
                cell = worksheet.cell(row=row_idx, column=col_idx)
                cell.alignment = wrap_align
                if highlight_debtors:
                    if individual:
                        # Подсвечиваем ВСЮ строку, если есть долг
                        if has_debt_in_row:
                            cell.fill = red_fill
                    else:
                        # Подсвечиваем ТОЛЬКО ячейку с долгом (и только в колонках студентов)
                        if col_name in student_cols and is_debtor(row[col_name]):
                            cell.fill = red_fill

        # Автоподбор ширины столбцов
        for col_idx, col_name in enumerate(df.columns, start=1):
            max_length = max(
                df[col_name].astype(str).map(len).max(),
                len(str(col_name))
            )
            adjusted_width = min(max_length + 2, 50)
            worksheet.column_dimensions[get_column_letter(col_idx)].width = adjusted_width

"""###Создание папок для отчетов"""

def ensure_report_directory(group_name, report_type):
    """Создание папок для отчетов"""
    base_dir = 'Report'  # Базовая папка со всеми отчетами
    group_dir = os.path.join(base_dir, group_name)  # Папка с отчетами по группе
    report_dir = os.path.join(group_dir, report_type)  # Папка отчетов по типу

    if not os.path.exists(base_dir):
        os.makedirs(base_dir)
    if not os.path.exists(group_dir):
        os.makedirs(group_dir)
    if not os.path.exists(report_dir):
        os.makedirs(report_dir)

    return report_dir

# import shutil
# # shutil.rmtree("/content/АПИб-22-3")
# shutil.rmtree("/content/Report")

"""### Вывод сегдняшней даты"""

from datetime import datetime
now = datetime.now()
date_now = now.strftime("%d_%m_%Y")
date_now

"""###Отчет по должникам"""

def report_debtors(df: pd.DataFrame, group_name: str, last_semesters=1):
    """Улучшенный отчет по должникам"""
    report_type = 'Должники'
    report_dir = ensure_report_directory(group_name, report_type)

    # Определяем уникальные семестры
    unique_semesters = df['Семестр'].unique()
    semester_numbers = []

    for semester in unique_semesters:
        match = re.search(r'(\d+)\s+семестр', str(semester))
        if match:
            semester_numbers.append(int(match.group(1)))

    if not semester_numbers:
        print("Семестры не найдены")
        return

    # Берем последние N семестров
    target_semesters = sorted(semester_numbers)[-last_semesters:]

    debt_data = []
    students = [col for col in df.columns if col not in ['Дисциплина', 'Тип', 'Семестр']]

    for target_semester in target_semesters:
        semester_df = df[df['Семестр'].str.contains(f"{target_semester} семестр", na=False)]

        for _, row in semester_df.iterrows():
            for student in students:
                grade = str(row[student]).lower()
                if grade in ['неуд', 'н/а', 'н/з', '']:
                    debt_data.append({
                        'Студент': student,
                        'Дисциплина': row['Дисциплина'],
                        'Тип': row['Тип'],
                        'Семестр': row['Семестр'],
                        'Оценка': row[student]
                    })

    if debt_data:
        debt_df = pd.DataFrame(debt_data)
        output_file = os.path.join(report_dir, f'должники_{last_semesters}_семестр_{group_name}_{date_now}.xlsx')
        df_to_excel_autoresize(debt_df, output_file, highlight_debtors=False)
        print(f"Отчет по должникам сохранен: {output_file}")
        print(f"Найдено {len(debt_data)} долгов за последние {last_semesters} семестра(ов)")
    else:
        print(f"Должников за последние {last_semesters} семестра(ов) не найдено")

"""#### По номеру семестра"""

def report_debtors_num_sem(df: pd.DataFrame, group_name: str, num_sem):
    """Улучшенный отчет по должникам"""
    report_type = 'Должники'
    report_dir = ensure_report_directory(group_name, report_type)

    # Определяем уникальные семестры
    unique_semesters = df['Семестр'].unique()
    semester_numbers = []

    for semester in unique_semesters:
        match = re.search(r'(\d+)\s+семестр', str(semester))
        if match:
            semester_numbers.append(int(match.group(1)))

    if not semester_numbers:
        print("Семестры не найдены")
        return

    debt_data = []
    students = [col for col in df.columns if col not in ['Дисциплина', 'Тип', 'Семестр']]


    semester_df = df[df['Семестр'].str.contains(f"{num_sem} семестр", na=False)]

    for _, row in semester_df.iterrows():
        for student in students:
            grade = str(row[student]).lower()
            if grade in ['неуд', 'н/а', 'н/з', '']:
                debt_data.append({
                    'Студент': student,
                    'Дисциплина': row['Дисциплина'],
                    'Тип': row['Тип'],
                    'Семестр': row['Семестр'],
                    'Оценка': row[student]
                })

    if debt_data:
        debt_df = pd.DataFrame(debt_data)
        output_file = os.path.join(report_dir, f'должники_{num_sem}_семестр_{group_name}_{date_now}.xlsx')
        df_to_excel_autoresize(debt_df, output_file, highlight_debtors=False)
        print(f"Отчет по должникам сохранен: {output_file}")
        print(f"Найдено {len(debt_data)} долгов за {num_sem} семестр")
    else:
        print(f"Должников за {num_sem} семестр не обнаружено")

"""###Отчет за весь период"""

def report_full_period(df: pd.DataFrame, group_name: str, individual=False):
    """Полный отчет за весь период обучения"""
    report_type = 'Весь период'
    report_dir = ensure_report_directory(group_name, report_type)

    if individual:
        # Индивидуальные отчеты по студентам
        students = [col for col in df.columns if col not in ['Дисциплина', 'Тип', 'Семестр']]
        for student in students:
            student_data = df[['Семестр', 'Дисциплина', 'Тип', student]].copy()
            student_data = student_data.rename(columns={student: 'Оценка'})
            output_file = os.path.join(report_dir, f'{student}_весь_период_{date_now}.xlsx')
            df_to_excel_autoresize(student_data, output_file, individual=individual)
        print(f"Полные индивидуальные отчеты сохранены в: {os.path.join(group_name, report_dir)}")

    else:
        # Общий отчет по группе — с добавлением среднего балла
        df_with_avg = df.copy()

        # Определяем колонки студентов
        student_cols = [col for col in df.columns if col not in ['Дисциплина', 'Тип', 'Семестр']]

        # Считаем средний балл по каждому студенту
        avg_row = {}
        avg_row['Дисциплина'] = 'Средний балл'
        avg_row['Тип'] = ''
        avg_row['Семестр'] = ''

        for student in student_cols:
            scores = df[student].apply(grade_to_score)
            avg_score = scores.mean()
            # Округляем до 2 знаков (например, 4.33)
            avg_row[student] = round(avg_score, 2)

        # Добавляем строку в конец
        df_with_avg = pd.concat([df_with_avg, pd.DataFrame([avg_row])], ignore_index=True)

        output_file = os.path.join(report_dir, f'весь_период_группа_{group_name}_{date_now}.xlsx')
        df_to_excel_autoresize(df_with_avg, output_file, individual=individual)

        print(f"Полный общий отчет сохранен в: {os.path.join(group_name, report_dir)}")

"""###Отчет по семестрам"""

def report_by_semester(df: pd.DataFrame, group_name: str, semester_number: int, individual=False):
    """Отчет по конкретному семестру"""
    report_type = 'Посеместровые отчеты'
    report_dir = ensure_report_directory(group_name, report_type)

    # Фильтрация по семестру
    semester_df = df[df['Семестр'].str.contains(f"{semester_number} семестр", na=False)].copy()

    if individual:
        # Индивидуальные отчеты по студентам
        students = [col for col in df.columns if col not in ['Дисциплина', 'Тип', 'Семестр']]

        for student in students:
            student_data = semester_df[['Дисциплина', 'Тип', student]].copy()
            student_data = student_data.rename(columns={student: 'Оценка'})
            output_file = os.path.join(report_dir, f'{student}_{semester_number}_семестр_{date_now}.xlsx')
            df_to_excel_autoresize(student_data, output_file)

    else:
        # Общий отчет по семестру
        output_file = os.path.join(report_dir, f'отчет_{semester_number}_семестр_{group_name}_{date_now}.xlsx')
        df_to_excel_autoresize(semester_df, output_file)

    print(f"Отчет за {semester_number} семестр сохранен")

"""###Генерация пдф"""

def generate_pdf_report(df: pd.DataFrame, title: str, filename: str):
    """Генерация PDF отчета (альтернатива Excel)"""
    doc = SimpleDocTemplate(filename, pagesize=A4)
    elements = []

    # Заголовок
    styles = getSampleStyleSheet()
    title_para = Paragraph(title, styles['Title'])
    elements.append(title_para)
    elements.append(Spacer(1, 12))

    # Преобразуем DataFrame в таблицу
    data = [df.columns.tolist()] + df.values.tolist()
    table = Table(data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
    ]))
    elements.append(table)
    doc.build(elements)

"""### Графики

Уникальные оценки:
- зач.
- н/а
- н/з
- неуд.
- отл.
- уд.
- хор.
"""

def grade_to_score(grade: str) -> int:
    """Преобразует текстовую оценку в числовой балл (2–5)"""
    g = str(grade).strip().lower()
    if g in {'отл.', 'зач.'}:
        return 5
    elif g in {'хор.'}:
        return 4
    elif g in {'уд.'}:
        return 3
    elif g in {'н/з', 'неуд.', 'н/а', ''}:
        return 2
    else:
        # На случай неизвестной оценки — считаем долгом
        return 2

def is_success(grade: str) -> bool:
    """Абсолютная успеваемость: оценка ≥ 3 (включая зачёты)"""
    return grade_to_score(grade) >= 3

def is_quality(grade: str, assessment_type: str) -> bool:
    """Качественная успеваемость: '4' или '5', НЕ включая зачёты"""
    g = str(grade).strip().lower()
    # Только экзамены и зачёты с оценкой
    if 'зачет с оценкой' in assessment_type.lower():
      return g in {'отл.', 'хор.', 'отлично', 'хорошо'}
    elif 'зачет' in assessment_type.lower() or 'зач.' in g:
        return False
    return g in {'отл.', 'хор.', 'отлично', 'хорошо'}

from matplotlib.ticker import PercentFormatter
def generate_plots(df: pd.DataFrame, group_name: str, output_dir: str):
    """Построение всех 6 графиков по данным успеваемости"""
    os.makedirs(output_dir, exist_ok=True)

    # Извлекаем номер семестра из строки вида "1 семестр"
    def extract_semester(semester_str):
        match = re.search(r'(\d+)', str(semester_str))
        return int(match.group(1)) if match else None

    df = df.copy()
    df['sem_num'] = df['Семестр'].apply(extract_semester)
    df = df.dropna(subset=['sem_num']).copy()
    df['sem_num'] = df['sem_num'].astype(int)

    student_cols = [col for col in df.columns if col not in ['Дисциплина', 'Тип', 'Семестр', 'sem_num']]

    # === 1. Абсолютная и качественная успеваемость по семестрам ===
    semesters = sorted(df['sem_num'].unique())
    au_list, kz_list = [], []

    for sem in semesters:
        sem_df = df[df['sem_num'] == sem]
        total_students = len(student_cols)

        # Абсолютная успеваемость
        success_count = sem_df[student_cols].applymap(is_success).sum().sum()
        au = success_count / (total_students * len(sem_df)) * 100

        # Качественная успеваемость
        kz_count = 0
        for _, row in sem_df.iterrows():
            for student in student_cols:
                if is_quality(row[student], row['Тип']):
                    kz_count += 1
        kz = kz_count / (total_students * len(sem_df)) * 100

        au_list.append(au)
        kz_list.append(kz)

    plt.figure(figsize=(10, 6))
    plt.plot(semesters, au_list, marker='o', label='Абсолютная успеваемость')
    plt.plot(semesters, kz_list, marker='s', label='Качественная успеваемость')
    plt.title('Успеваемость по семестрам')
    plt.xlabel('Семестр')
    plt.ylabel('Проценты')
    plt.gca().yaxis.set_major_formatter(PercentFormatter())
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(output_dir, '1_успеваемость_по_семестрам.png'), bbox_inches='tight')
    plt.show()
    plt.close()

    # === 2. Общее количество долгов по семестрам ===
    debt_counts = []
    for sem in semesters:
        sem_df = df[df['sem_num'] == sem]
        debt_count = sem_df[student_cols].applymap(lambda x: grade_to_score(x) == 2).sum().sum()
        debt_counts.append(debt_count)

    plt.figure(figsize=(10, 6))
    plt.bar(semesters, debt_counts, color='salmon')
    plt.title('Количество долгов по семестрам')
    plt.xlabel('Семестр')
    plt.ylabel('Число долгов')
    plt.grid(axis='y')
    plt.show()
    plt.savefig(os.path.join(output_dir, '2_долги_по_семестрам.png'), bbox_inches='tight')
    plt.close()

    # === 3. Средний балл по каждому студенту за выбранный семестр (например, 5-й) ===
    selected_sem = 5
    if selected_sem in semesters:
        sem_df = df[df['sem_num'] == selected_sem]
        avg_scores = {}
        for student in student_cols:
            scores = sem_df[student].apply(grade_to_score)
            avg_scores[student] = scores.mean()

        students_short = [s.split()[0] for s in avg_scores.keys()]  # Только имена
        plt.figure(figsize=(12, 6))
        plt.bar(students_short, avg_scores.values(), color='lightgreen')
        plt.title(f'Средний балл по студентам (семестр {selected_sem})')
        plt.xlabel('Студент')
        plt.ylabel('Средний балл')
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.show()
        plt.savefig(os.path.join(output_dir, f'3_средний_балл_семестр_{selected_sem}.png'))
        plt.close()

    # === 4. Динамика среднего балла по студентам по семестрам ===
    avg_by_sem_student = {}
    for student in student_cols:
        avg_by_sem = []
        for sem in semesters:
            sem_df = df[df['sem_num'] == sem]
            if not sem_df.empty:
                scores = sem_df[student].apply(grade_to_score)
                avg_by_sem.append(scores.mean())
            else:
                avg_by_sem.append(None)
        avg_by_sem_student[student] = avg_by_sem

    plt.figure(figsize=(12, 7))
    for student, avgs in avg_by_sem_student.items():
        plt.plot(semesters, avgs, marker='o', label=student.split()[0])
    plt.title('Динамика среднего балла по студентам')
    plt.xlabel('Семестр')
    plt.ylabel('Средний балл')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True)
    plt.tight_layout()
    plt.show()
    plt.savefig(os.path.join(output_dir, '4_динамика_среднего_балла.png'))
    plt.close()

    # === 5. Количество долгов по отдельной дисциплине (например, "Иностранный язык") ===
    target_subject = "Большие данные в цифровой экономике"
    subject_rows = df[df['Дисциплина'].str.contains(target_subject, case=False, na=False)]
    if not subject_rows.empty:
        debt_per_row = subject_rows[student_cols].applymap(lambda x: grade_to_score(x) == 2).sum(axis=1)
        sems = subject_rows['sem_num'].tolist()
        debts = debt_per_row.tolist()

        plt.figure(figsize=(8, 5))
        plt.bar(sems, debts, color='coral')
        plt.title(f'Долги по дисциплине: {target_subject}')
        plt.xlabel('Семестр')
        plt.ylabel('Число долгов')
        plt.xticks(sems)
        plt.grid(axis='y')
        plt.show()
        plt.savefig(os.path.join(output_dir, f'5_долги_по_дисциплине_{target_subject.replace(" ", "_")}.png'))
        plt.close()

    # === 6. Средняя оценка по отдельной дисциплине за отдельный семестр (например, "Прикладная математика", семестр 1) ===
    target_subject2 = "Прикладная математика"
    target_sem2 = 1
    mask = (df['Дисциплина'].str.contains(target_subject2, case=False, na=False)) & (df['sem_num'] == target_sem2)
    row = df[mask]
    if not row.empty:
        scores = row[student_cols].iloc[0].apply(grade_to_score)
        avg_score = scores.mean()

        plt.figure(figsize=(6, 4))
        plt.bar(['Средняя оценка'], [avg_score], color='steelblue')
        plt.title(f'{target_subject2}\n(семестр {target_sem2})')
        plt.ylim(2, 5)
        plt.ylabel('Балл')
        for i, v in enumerate([avg_score]):
            plt.text(i, v + 0.05, f'{v:.2f}', ha='center')
        plt.show()
        plt.savefig(os.path.join(output_dir, f'6_средняя_оценка_{target_subject2.replace(" ", "_")}_сем{target_sem2}.png'))
        plt.close()

"""###Константы"""

html_file = '/content/drive/MyDrive/PARIS/уник/7 сем/ВКР/scrap_portal/Кабинет куратора _ Образовательный портал МГТУ2.html'

"""##Выполнение"""

# Чтение и парсинг данных
with open(html_file, 'r', encoding='utf-8') as f:
    html_content = f.read()

df, group_name = parse_grade_data(html_content)

print(f"Обработана группа: {group_name}")
print(f"Размер DataFrame: {df.shape}")
print(f"Семестры: {df['Семестр'].unique()}")

# Генерация отчетов
report_full_period(df, group_name, individual=True)  # Индивидуальные отчеты
report_full_period(df, group_name, individual=False) # Общий отчет

unique_grades = set()
# Iterate over student columns (from the 4th column to the end)
for col in df.columns[3:]:
    unique_grades.update(df[col].unique())

# Convert to a sorted list for better readability
sorted_unique_grades = sorted(list(unique_grades))

print("Уникальные оценки:")
for grade in sorted_unique_grades:
    print(f"- {grade}")

df

# Отчеты по должникам
report_debtors(df, group_name, last_semesters=1)
report_debtors(df, group_name, last_semesters=2)

# Отчеты по должникам
report_debtors_num_sem(df, group_name, num_sem=4)

# Отчет по 5 семестру
report_by_semester(df, group_name, 5, individual=False)
report_by_semester(df, group_name, 5, individual=True)

report_dir = ensure_report_directory(group_name, 'Графики')
generate_plots(df, group_name, os.path.join(report_dir, 'Графики'))
print("✅ Все графики сохранены!")

report_dir = ensure_report_directory(group_name, 'Графики')
generate_plots(df, group_name, os.path.join(report_dir, 'Графики'))
print("✅ Все графики сохранены!")

"""### Требования к наименованию отчетов

Название отчетов строится по следующей схеме:

Индивидуальные -- ФИО_тип отчета_дата создания

Общие -- тип отчета_группа_дата создания

Для отчета по должникам -- тип отчета_номер семестра_группа_дата создания
"""

df